### ISSUE TITLE
Throw proper error when common.getDays() and common.copyDate() functions are invoked with invalid date params

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-health-modules#2]
This issue was raised as part of a [ticket](https://avni.freshdesk.com/a/tickets/3176)

## Fix needed:
1. Throw proper error when common.getDays() and common.copyDate() functions are invoked with invalid date params.
2. In the various organisations that have been impacted, 
    - Check the ruleTelemetry to find instances
    - correct the rules if needed to invoke the function with valid date for common.getDays() and common.copyDate() functions
3. Check data passed to these methods from health-modules code.  Fields under focus: DOB, enrolmentDateTime, LastMenstrualPeriod, etc..
4. upgrade avni-health-modules versions in webapp, client and rules-server

## Acceptance criteria

Instead of a generic non-meaningful message such as 
```
undefined is not an object (evaluating 't.getTime')
```
Ensure that error message shown is readable and helps implementers understand the root cause of an issue:
```
Invalid date value \'${date}\' specified for mandatory concept \'${fieldName}\' for entity \'${entity}\' with uuid \'${entityUUID}\'`
```

**Comment by himeshr** [comment]
Pending work: Handle errors corresponding to "Common.copyDate()"

**Comment by himeshr** [comment]
Have added checks before invoking the methods with invalid dates.
The dates sent are always mandatory fields, which should not be missing.
If there are any errors, then the error will now clearly specify which mandatory field is missing, and data corrections would have to be done if needed.

**Comment by himeshr** [comment]
@vinayvenu I'm not sure what more could be done here, please review and suggest.

**Comment by himeshr** [comment]
Pending task:
upgrade avni-health-modules versions in webapp, client and rules-server, if this passes codeReview

**Comment by mahalakshme** [comment]
@himeshr I feel it will be easier to have the invalid check(if mandatary concept and date invalid throw error) inside getObservationValue function in avni models because getting the value of date concepts I see is spread across avni-health-modules in several other places as well. I dont know if the error message will bubble up,  please check that.

### How to test:
- Create a user similar to maha@ashwini in prod env. Go to SAROJINI individual -> click on edit of Delivery program encounter -> go to last page. In prod it will store the error 'Cannot read property 'getTime' of undefined' in error_message column of RuleFailureTelemetry table.
- In prerelease it should store the error like 'Invalid date value {{value}} specified for mandatory concept {concept_name} for {entity type like Program enrolment, encounter, etc} with uuid {{uuid}}'. 

Note: I have added the entity type also in error message since that will help in fixing the rule. This is needed because sometimes in the rule, its just the entity that is passed and not the concept directly.

**Comment by mahalakshme** [comment]
Just updating whatever discussed, To keep getObservationValue lean we can just move the validations inside the functions, lmp and deliveryDate methods, and add the entity type in error message.

**Comment by himeshr** [comment]
> Pending task: upgrade avni-health-modules versions in webapp, client and rules-server, if this passes codeReview

Done in avni-client, wasn't required in rules-server or avni-webapp (they always refer to latest)

**Comment by himeshr** [comment]
@mahalakshme review this additional commit made to absord code review comments
https://github.com/avniproject/avni-health-modules/commit/3248c88b73ecdb9614b8a48dd853168498cb8597

**Comment by mahalakshme** [comment]
@himeshr we have not added `errIfLmpIsNotSet` to `dateOfDelivery`. I think it will help to add this in readme in someplace relevant or in a new page like Implementation Contracts. But if you think it will be too much to maintain it, leave it.

**Comment by himeshr** [comment]
> @himeshr we have not added `errIfLmpIsNotSet` to `dateOfDelivery`. I think it will help to add this in readme in someplace relevant or in a new page like Implementation Contracts. But if you think it will be too much to maintain it, leave it.

So, this is a new method that i introduced, which will error out in general. So anyone who wants to use it, should know that it throws an error if not set.

Whereas lmp method was old, and we introduced "errIfLmpIsNotSet" optional param, to ensure backward compatibility.

If you would want dateOfDelivery() to also have an optional "errIfDeliveryDateNotSet", then that's doable. Is that recommended?

**Comment by mahalakshme** [comment]
@himeshr okay then I think not needed, since whoever writes the rule can handle them via try catch block as well.

**Comment by mahalakshme** [comment]
@himeshr Ah! when you talked about backwards compatibility realised this is not backward compatible. `gestationalAgeAsOn ` should receive errIfLmpIsNotSet from user and default value for it need to be false. Else implementations like ashwini will break after the release since data from bahmni doesn't have expected fields. Else it will require fixing of implementations before the release which I dont think will happen. The implementation team can update the rules by sending true parameter for cases needed when they can/going forward. I suggest lets not pass true anywhere, instead get via parameter from user for `gestationalAgeAsOn`, `getVaccSchedule `, `getEnrolmentSummary `, etc., as well

**Comment by himeshr** [comment]
> @himeshr Ah! when you talked about backwards compatibility realised this is not backward compatible. `gestationalAgeAsOn ` should receive errIfLmpIsNotSet from user and default value for it need to be false. Else implementations like ashwini will break after the release since data from bahmni doesn't have expected fields. Else it will require fixing of implementations before the release which I dont think will happen. The implementation team can update the rules by sending true parameter for cases needed when they can/going forward. I suggest lets not pass true anywhere, instead get via parameter from user for `gestationalAgeAsOn`, `getVaccSchedule `, `getEnrolmentSummary `, etc., as well

Not valid, these would neways error out with undefine on .time() call if not for these checks.

**Comment by himeshr** [comment]
## Test scenario:

Refer to the ticket https://avni.freshdesk.com/a/tickets/3351 for test instructions.

#### Test scenario Details are as below:
Environment: prerelease
Org : ihmp
User : vedantr@ihmp
Individual uuid : d3434e37-61c6-4228-87ba-9b2c13764b2f
Soruce: 076ddb2d-a499-4314-af95-4178553d279b (EnrolmentSummary)

##### Steps to Reproduce:
**APK: Latest 6.1 release apk for pre-release environment**
1. login with vedantr@ihmp.
2. search for individual "test test".
3. sync and see rule failure.

##### Failure details
You should **not** get rule failure telemetry error message 
```
'Cannot read property 'getTime' of undefined'
```
But instead get a rule failure telemetry error message 
```
'Invalid date value \'${date}\' specified for mandatory concept \'${fieldName}\' for entity \'${entity}\' with uuid \'${entityUUID}\'
```
